# Configuration for nattmusikk-hele-dagen

# Path to the socket file opened by LiquidSoap. Used to communicate with the
# LiquidSoap server.
socketfile: "{{ socketfile }}"

# The name of the interactive.bool in LiquidSoap that this program is supposed
# to change.
liquidsoap_var_name: "{{ liquidsoap_var_name }}"

# Name of the Slack channel to restrain nattmusikk requests to
slack_channel: "{{ slack_channel }}"

{% block more_settings %}{% endblock %}
