{% extends "settings_base.yaml" %}
{% block explanation -%}
# Settings for nightmusic-all-day, used on the host which runs LiquidSoap
{% endblock %}

{% block more_settings %}
# Path to the socket file opened by LiquidSoap. Used to communicate with the
# LiquidSoap server.
socketfile: "{{ socketfile }}"

# The name of the interactive.bool in LiquidSoap that this program is supposed
# to change.
liquidsoap_var_name: "{{ liquidsoap_var_name }}"

# Slack-specific settings:
slack:
  # API Token
  token: "{{ token }}"

  # Which channel to post in
  channel: "{{ channel }}"

  # Username to post as
  username: "{{ username }}"

  # Avatar, given as an emoji
  icon_emoji: "{{ icon_emoji }}"


# Which port to use for listening for HTTP requests.
port: {{ port }}

# Whitelist of other computers which may communicate with this software.
allowed_remote_addresses:
{% for address in allowed_remote_addresses %}  - "{{ address }}"
{% endfor %}

{% endblock %}
