{% extends "settings_base.yaml" %}
{% block explanation -%}
# Settings for nightmusic-all-day, used on the host which provides the layer
# between Slack and the host running LiquidSoap.
{% endblock %}

{% block more_settings %}
# The port on which nightmusic-all-day on the host running LS is listening.
port: {{ port }}

# The host at which nightmusic-all-day is running
host: "{{ host }}"
{% endblock %}
